[package]
name = "atlas"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.17.1"
bytes = "1.11.0"
smol_str = "0.3.4"
smallvec = "1.15.1"
parking_lot = "0.12.5"
tokio = { version = "1.49.0", features = ["full"] }
bincode = "=2.0.1"
futures = "0.3.31"